### ISSUE TITLE
Order book updates not being received

### ISSUE THREAD

**Issue by spcfran** [Pr0x1m4/kraken-ws-playground#1]
When I subscribe to order book
```javascript
{
  "event": "subscribe",
  "pair": [ "ETH/EUR" ],
  "subscription": { "name": "book" }
}
```
I receive fist the subscription status confirmation and then the initial snapshot, but no further 'delta' updates (as per [kraken docs](https://www.kraken.com/features/websocket-api#message-book)), only heartbeats.

They are not coming through the socket so it doesn't seem to be a problem in your app, I guess what I'm asking if is you have come across to this?

**Comment by spcfran** [comment]
nevermind, suddenly started working! Guess they fixed on their end

**Comment by Pr0x1m4** [comment]
Looks like it, I tried to file an issue with their support team but it looks like they got it fixed.
